import type { EventRecord } from './EventsContext';

// Demo data seeded on first load so the dashboards look populated. Events created
// by an organizer start at zero; these provide the rich/analytical look.
// The demo organizer account is organizer@eventnic.com; the demo nominee is "Sarah Nominee".

const DEMO_ORGANIZER_EMAIL = 'organizer@eventnic.com';
const DEMO_ORGANIZER_NAME = 'Markus DJ';

const now = Date.now();
const day = 86_400_000;

export const SEED_EVENTS: EventRecord[] = [
  {
    id: 'seed-techpulse',
    slug: 'techpulse-global-2024',
    title: 'TechPulse Global 2024',
    category: 'conference',
    locationType: 'physical',
    location: 'San Francisco Convention Center',
    description:
      'The premier gathering for builders, founders, and investors shaping the next decade of technology. Three days of keynotes, workshops, and deep networking.',
    coverImage: '/images/stitch-9cf7f93ffe1c0a00.png',
    date: 'Oct 12, 2024',
    time: '09:00 AM',
    organizerEmail: DEMO_ORGANIZER_EMAIL,
    organizerName: DEMO_ORGANIZER_NAME,
    speakers: [
      { id: 'sp1', name: 'Sarah Jenkins', title: 'CTO, CloudScale AI' },
      { id: 'sp2', name: 'David Chen', title: 'Founder, Nexus Systems' },
    ],
    votingEnabled: true,
    votingCategories: [
      {
        id: 'cat-startup',
        name: 'Best Tech Startup',
        nominees: [
          { id: 'nom-sarah', name: 'Sarah Nominee', description: 'AI-driven analytics platform', votes: 1402 },
          { id: 'nom-nexus', name: 'Nexus Systems', description: 'Next-gen database architecture', votes: 1280 },
          { id: 'nom-cloud', name: 'CloudScale AI', description: 'Distributed ML infrastructure', votes: 960 },
          { id: 'nom-quantum', name: 'Quantum Tech', description: 'Edge compute fabric', votes: 540 },
        ],
      },
      {
        id: 'cat-founder',
        name: 'Most Innovative Founder',
        nominees: [
          { id: 'nom-f1', name: 'Elena Solis', description: 'Reimagining fintech rails', votes: 1120 },
          { id: 'nom-sarah2', name: 'Sarah Nominee', description: 'Builder & creator', votes: 890 },
          { id: 'nom-f3', name: 'James Wu', description: 'Robotics for logistics', votes: 770 },
        ],
      },
    ],
    ticketTiers: [
      { id: 'tt1', name: 'Early Bird', price: 499, quantity: 450, sold: 450 },
      { id: 'tt2', name: 'General Admission', price: 899, quantity: 1000, sold: 820 },
      { id: 'tt3', name: 'VIP Backstage', price: 1499, quantity: 350, sold: 180 },
    ],
    agenda: [
      { id: 'ag1', title: 'Registration & Coffee', start: '08:00', end: '09:00', description: 'Welcome attendees and distribute badges.' },
      { id: 'ag2', title: 'Opening Keynote', start: '09:15', end: '10:30', description: 'A deep dive into upcoming technological shifts.' },
    ],
    rsvpEnabled: false,
    status: 'published',
    createdAt: now - 40 * day,
  },
  {
    id: 'seed-wellness',
    slug: 'corporate-wellness-expo',
    title: 'Corporate Wellness Expo',
    category: 'exhibition',
    locationType: 'physical',
    location: 'Chicago, IL',
    description: 'A full-day expo connecting HR leaders with the best in workplace wellness and benefits.',
    coverImage: '/images/stitch-6bf38ab87efad932.png',
    date: 'Nov 12, 2024',
    time: '10:00 AM',
    organizerEmail: DEMO_ORGANIZER_EMAIL,
    organizerName: DEMO_ORGANIZER_NAME,
    speakers: [{ id: 'sp3', name: 'Dr. Amara Osei', title: 'Wellness Researcher' }],
    votingEnabled: false,
    votingCategories: [],
    ticketTiers: [
      { id: 'tt4', name: 'Standard', price: 120, quantity: 700, sold: 310 },
      { id: 'tt5', name: 'Pro Pass', price: 280, quantity: 300, sold: 140 },
    ],
    agenda: [],
    rsvpEnabled: false,
    status: 'published',
    createdAt: now - 20 * day,
  },
  {
    id: 'seed-aidesign',
    slug: 'ai-design-workshop',
    title: 'AI Design Workshop',
    category: 'workshop',
    locationType: 'online',
    location: 'Online',
    description: 'Hands-on workshop on designing with generative AI tools, from prototype to production.',
    coverImage: '/images/stitch-4d8bd40188625896.png',
    date: 'Dec 05, 2024',
    time: '01:00 PM',
    organizerEmail: DEMO_ORGANIZER_EMAIL,
    organizerName: DEMO_ORGANIZER_NAME,
    speakers: [],
    votingEnabled: false,
    votingCategories: [],
    ticketTiers: [{ id: 'tt6', name: 'Seat', price: 75, quantity: 200, sold: 195 }],
    agenda: [],
    rsvpEnabled: true,
    status: 'published',
    createdAt: now - 10 * day,
  },
  {
    id: 'seed-summit',
    slug: 'global-tech-summit-2026',
    title: 'Global Tech Summit 2026',
    category: 'conference',
    locationType: 'hybrid',
    location: 'Austin, TX',
    description: 'A forward-looking summit on AI, climate tech, and the future of work.',
    coverImage: '/images/stitch-f76be2086127355c.png',
    date: 'Mar 18, 2026',
    time: '09:00 AM',
    organizerEmail: 'sarah.jenkins@summit.com',
    organizerName: 'Sarah Jenkins',
    speakers: [],
    votingEnabled: false,
    votingCategories: [],
    ticketTiers: [{ id: 'tt7', name: 'General Admission', price: 350, quantity: 2000, sold: 0 }],
    agenda: [],
    rsvpEnabled: false,
    status: 'pending',
    createdAt: now - 2 * day,
  },
  {
    id: 'seed-neon',
    slug: 'neon-nights-festival',
    title: 'Neon Nights Festival',
    category: 'concert',
    locationType: 'physical',
    location: 'Miami, FL',
    description: 'An electric night of live electronic music across three stages.',
    coverImage: '/images/stitch-d8dc67c970e41785.png',
    date: 'Jul 04, 2026',
    time: '06:00 PM',
    organizerEmail: DEMO_ORGANIZER_EMAIL,
    organizerName: DEMO_ORGANIZER_NAME,
    speakers: [],
    votingEnabled: false,
    votingCategories: [],
    ticketTiers: [{ id: 'tt8', name: 'GA', price: 89, quantity: 5000, sold: 0 }],
    agenda: [],
    rsvpEnabled: false,
    status: 'pending',
    createdAt: now - 1 * day,
  },
];
